#!/bin/zsh

# Create a unique title 
unique_title=$(openssl rand -base64 9 | tr -dc 'a-zA-Z0-9' | cut -c -12)

# Capture the screenshot and save to a file
output=~/note-vault/imgs/${unique_title}_screenshot.png 
screencapture -i "$output"

# Echo the absolute path of the screenshot file
echo "Screenshot saved to: $output "

